### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Felli** [GreenMeteor/humhub-onlinegroups-module#4]
The following is the set Roadmap for this module!

- [x] Need to fix {#1)
- [ ] Online Group members display (#2)
- [ ] Code Cleaning (#3)
- [x] ~~Find a better way of implementing `'OnlineGroups' => $query->all(),`~~
- [x] Search for specific online group instead of all online groups. (#5)
